function param = parameterInfo

% Copyright 2012 The MathWorks, Inc.

param = [ ...
  nnetParamInfo('ymin','Y Minimum','nntype.num_scalar',-1,...
  'Minimum value for each row of Y.'), ...
  nnetParamInfo('ymax','Y Maximum','nntype.num_scalar',1,...
  'Maximum value for each row of Y.'), ...
  ];
