function param = parameterInfo

% Copyright 2012 The MathWorks, Inc.

param = [ ...
  nnetParamInfo('ymean','Y Mean','nntype.num_scalar',0,...
  'Mean for each row of Y.'), ...
  nnetParamInfo('ystd','Y Standard Deviation','nntype.pos_scalar',1,...
  'Standard deviation for each row of Y.'), ...
  ];
