function param = parameterInfo

% Copyright 2012 The MathWorks, Inc.

param = [...
  nnetParamInfo('regularization','Regularization Ratio','nntype.real_0_to_1',0,...
  'Fraction of performance associated with regularization.'),...
  nnetParamInfo('normalization','Normalization','nntype.error_norm_mode','none',...
  'The kind of error normalization relative to target ranges.')
  ];
